Initialiser les données de localisation (longitude, latitude) pour les signalements : données en base et migration
MTES-MCT/stop-punaises pull request #319
Opened 2023-06-12 10:00 UTC by hmeneuvrier

## Ticket

#318    

## Description
Enregistrement de la géolocalisation pour les signalements. Première étape nécessaire pour la cartographie

## Changements apportés
* Ajout d'un champ geoloc à la table signalement
* Création d'une commande qui ajoute la géolocalisation à tous les signalements existants
* Ajout de paramètre au formulaire front pour enregistrer la localisation lors de la création d'un nouveau signalement

## Tests
- [] Jouer la commande "`symfony console app:geolocate`" et vérifier en base que les coordonnées ont bien été ajoutées aux signalements existants
- [] Créer un nouveau signalement, et vérifier en base que sa géolocalisation a bien été enregistrée

2023-06-12 14:33 UTC, emilschn approved these changes
Ok pour relecture, ok pour tests (penser à faire `npm run watch` avant)

2023-06-13 07:44 UTC, hmeneuvrier commented on src/Form/SignalementType.php
> +            ])
ajouter également le ModelTransformer, voir s'il y a un js associé, et faire le cas de test

2023-06-13 07:44 UTC, hmeneuvrier commented
Ajouter test unitaire/fonctionnel ?

2023-06-13 16:03 UTC, sfinx13 requested changes

2023-06-13 16:03 UTC, sfinx13 commented on src/Command/GeolocateCommand.php
> +    private Client $httpClient;
Utiliser le HttpClient de Symfony au lieu de Guzzle

2023-06-13 16:04 UTC, sfinx13 requested changes

2023-06-14 09:18 UTC, hmeneuvrier commented on src/Command/GeolocateCommand.php
> +    private Client $httpClient;
ok

2023-06-14 09:19 UTC, hmeneuvrier commented on src/Command/GeolocateCommand.php
> +        $this->httpClient = new Client();
ok

2023-06-14 14:46 UTC, sfinx13 approved these changes

2023-06-14 15:18 UTC, merged