[Front] Ajout formulaire de contact
MTES-MCT/stop-punaises pull request #322
Opened 2023-06-20 14:49 UTC by emilschn

## Ticket

#321    

## Description
Ajout d'un formulaire de contact front

## Tests
- [ ] Ne pas remplir certains champs et vérifier que le formulaire ne s'envoie pas
- [ ] Envoyer un formulaire de contact correct et vérifier dans mail catcher, dans la source du message

2023-06-22 10:03 UTC, sfinx13 requested changes

2023-06-22 10:03 UTC, sfinx13 commented on src/FormHandler/ContactFormHandler.php
> +        string $message,
Handle un form, voir mon commentaire plus haut, récupérer les infos dans la méthode handle

2023-06-22 14:55 UTC, hmeneuvrier reviewed
Tests OK

2023-06-22 14:55 UTC, hmeneuvrier commented on src/Controller/Front/HomeController.php
> +                $this->addFlash('error', 'Une erreur a empêché l\'envoi de votre message');
c'est peut-être un peu too much pour un formulaire à 3 champs, mais on pourrait indiquer quel champ est invalide

2023-06-22 14:55 UTC, hmeneuvrier commented on src/Form/ContactType.php
> +                    new Assert\NotBlank(message: 'Merci de renseigner votre nom complet.'),
Je n'ai pas vu ces messages d'erreur

2023-06-22 15:48 UTC, emilschn commented
Merci pour vos retours ! C'est traité :)

2023-06-23 14:56 UTC, sfinx13 approved these changes

2023-06-26 09:59 UTC, sfinx13 approved these changes

2023-06-26 09:59 UTC, merged