Feature/320 add carto
MTES-MCT/stop-punaises pull request #323
Opened 2023-06-20 15:39 UTC by hmeneuvrier

## Ticket

#NumIssue   

## Description
Description de la modification apportée

## Changements apportés
* Liste
* des changements techniques
* apportés

## Tests
- [] Les différentes étapes
- [] des tests à faire

2023-06-23 09:51 UTC, emilschn requested changes

2023-06-23 09:51 UTC, emilschn commented on public/js/maps.js
> +window.onload = async () => {
supprimer

2023-06-23 09:51 UTC, emilschn commented on src/Service/Signalement/CartoStatutService.php
> +            $date4months = $date->modify('-4 month');
date4monthsAgo

2023-06-26 10:22 UTC, sfinx13 requested changes

2023-06-26 10:22 UTC, sfinx13 commented on assets/controllers/weekly_slider.js
> +  const startDate = new Date(2021, 0, 2)
SI j'ai bien compris, on va récupérer des signalements antérieur à 2021
Pensez à mettre à jour cette date ?

2023-06-26 10:22 UTC, sfinx13 commented on src/Service/Signalement/CartoStatutService.php
> +class CartoStatutService
CartoStatutCalculator

2023-06-26 10:22 UTC, sfinx13 commented on src/Service/Signalement/CartoStatutService.php
> +    public function calculateStatut(array $signalements, \DateTimeImmutable $date): array
calculate

2023-06-26 17:17 UTC, sfinx13 requested changes

2023-06-26 19:09 UTC, hmeneuvrier commented on assets/controllers/weekly_slider.js
> +  const startDate = new Date(2021, 0, 2)
Oui, on va récupérer des signalements antérieurs à 2021, mais on verra leur statut à partir du 1er janvier 2021. On a vu avec Arnaud

2023-06-27 09:32 UTC, sfinx13 approved these changes

2023-06-27 09:32 UTC, merged