[CRON] Cloture automatique des signalements en traitement pro après 30 jours d'inactivité
MTES-MCT/stop-punaises pull request #347
Opened 2023-08-11 10:50 UTC by emilschn

## Ticket

#336    

## Description
Cloture automatique des signalements en traitement pro après 30 jours d'inactivité

## Tests
- [ ] Créer 5 signalements avec traitement pro dans territoire ouvert (13)
  - [ ] Signalement 1 : En BDD, changer la date de dernier événement à plus de 30 jours
  - [ ] Signalement 2 : Se connecter en back-office avec entreprise, ajouter une estimation, accepter avec l'usager
  - [ ] Signalement 3 : Se connecter en back-office avec entreprise, ajouter une estimation, refuser avec l'usager
  - [ ] Signalement 4 : Se connecter en back-office avec entreprise, ajouter une estimation, ne pas répondre
  - [ ] En BDD, changer la date de tous les événements à plus de 30 jours
  - [ ] Signalement 5 : Créer et ne rien toucher
- [ ] Exécuter la commande `make console app="send-reminders"`
- [ ] Les signalements 1, 3 et 4 doivent se fermer. 
- [ ] Les signalements 2 et 5 doivent rester ouverts.

2023-08-17 10:51 UTC, hmeneuvrier commented
Tests OK (c'était laborieux)

2023-08-17 10:54 UTC, hmeneuvrier requested changes

2023-08-17 10:54 UTC, hmeneuvrier commented on src/Command/SendRemindersCommand.php
> +        $signalement->setClosedAt(new \DateTimeImmutable());
@emilschn est-ce que là aussi il ne faudrait pas mettre à jour l'uuid public, car en prenant le lien dans un mail plus ancien, l'usager peut à nouveau accéder à sa page de signalement, et accepter une estimation s'il n'avait pas répondu (par exemple)

2023-08-18 09:13 UTC, emilschn commented on src/Command/SendRemindersCommand.php
> +        $signalement->setClosedAt(new \DateTimeImmutable());
@hmeneuvrier c'est corrigé !

2023-08-18 13:51 UTC, hmeneuvrier approved these changes
Re-relecture OK

2023-08-18 13:58 UTC, hmeneuvrier commented
Re-test OK !
Je merge

2023-08-18 13:58 UTC, merged