[BO] Créer le listing ERP / transport dans le BO
MTES-MCT/stop-punaises pull request #392
Opened 2023-10-18 08:26 UTC by hmeneuvrier

## Ticket

#373    

## Description
Création de la liste des signalements ERP/Transports https://github.com/MTES-MCT/stop-punaises/wiki/listes-de-signalements#signalements-erp-et-transports
Création du menu et de la carte sur le dashboard pour les admins

## Changements apportés
* Création des templates twigs pour la liste, la modale et le filtre
* Ajout d'un item dans le menu et d'une carte dans le dashboard
* Ajout d'extensions twig pour le bon affichage
* Ajout d'une fonction dans le repository pour récupérer les signalements ERP et transports, et modification d'autres fonctions
* Ajout d'une route erp-transports

## Pré-requis

`make create-db`

## Tests
- [ ] Se connecter en admin
- [ ] Vérifier sur le dashboard qu'il y a une nouvelle carte pour les ERP et les transports et qu'elle redirige vers la nouvelle liste
- [ ] Vérifier aussi le fonctionnement du nouvel item dans le menu
- [ ] Vérifier l'affichage de la liste, et les 4 possibilités de filtre
- [ ] Vérifier l'ouverture de la modale
- [ ] Se connecter pas en admin
- [ ] vérifier qu'on n'y a pas accès

2023-10-18 15:20 UTC, sfinx13 commented
@hmeneuvrier j'ai réussi a accéder en tant qu'entreprise en passant par l'url

2023-10-19 08:49 UTC, emilschn requested changes

2023-10-19 08:49 UTC, emilschn commented on templates/signalement_list/modal-signalement-erp-transports.html.twig
> +    Type : label "transport" (couleur info) - nom du transport
A supprimer

2023-10-19 08:55 UTC, emilschn commented
Tests ok (en dehors du retour de Saidi)

2023-10-20 07:15 UTC, hmeneuvrier commented
@sfinx13 @emilschn vos retours sont traités

2023-10-20 07:30 UTC, emilschn approved these changes

2023-10-20 15:24 UTC, sfinx13 approved these changes

2023-10-20 15:24 UTC, merged