[FO] Créer le formulaire ERP et TRANSPORT
MTES-MCT/stop-punaises pull request #396
Opened 2023-10-20 09:25 UTC by sfinx13

## Ticket

#374    

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2023-10-20 09:30 UTC, sfinx13 commented on templates/signalement_list/modal-signalement-erp-transports.html.twig
> +
@hmeneuvrier j'étais parti de ta branche, j'ai donc fait un rebase  mais j'ai ce morceau dans la PR (tu l'as supprimé ou pas encore ?)

2023-10-20 15:34 UTC, sfinx13 commented on src/Service/Upload/UploadHandlerService.php
> +                if ($file->getError()) {
Je renvoie un tableau vide pour éviter des régression avec les autres features. Il faudra gérer l’erreur autrement

2023-10-20 15:57 UTC, hmeneuvrier commented on templates/signalement_list/modal-signalement-erp-transports.html.twig
> +
je l'ai supprimé

2023-10-23 07:26 UTC, hmeneuvrier commented
Test : tout est OK, j'ai revérifié également tous les workflows de la PR d'Emilien, tout fonctionne bien.

J'ai juste un doute sur les photos. J'ai une 404 quand j'essaie de les ouvrir depuis le BO, mais c'est également le cas sur un signalement "logement". C'est du à ma config en local ?

2023-10-23 07:30 UTC, hmeneuvrier commented
Je viens de voir un truc (mais qui n'a rien à voir avec la PR), quand on signale un logement dans un territoire non ouvert on n'a pas la geoloc, je vais créer un ticket

2023-10-23 08:16 UTC, hmeneuvrier requested changes

2023-10-23 08:16 UTC, hmeneuvrier commented on src/DataFixtures/Files/Signalement.yml
> +  transport_line_number: "Petit train"
ah ah, c'est cool ce type de transport ! :D j'imagine une panique "punaises de lit" dans un petit train touristique

2023-10-23 15:47 UTC, sfinx13 commented on assets/controllers/component_search_address.js
> +    $('#adresse_detail').toggleClass('fr-hidden');
Dans le dsfr c'est un œil barré

2023-10-23 16:04 UTC, hmeneuvrier commented on src/Form/SignalementErpType.php
> +                    'maxlength' => '100',
le `maxlength` est à déplacer dans `attr`

2023-10-23 16:04 UTC, hmeneuvrier commented on src/Form/SignalementErpType.php
> +                    'minlength' => '5',
le `maxlength` et `minlength` sont  à déplacer dans `attr`

2023-10-23 16:07 UTC, sfinx13 commented on src/Service/Upload/UploadHandlerService.php
> +                if ($file->getError()) {
Envoyer une exception personnalisé et catcher l'exception partout ou c'est utilisé

2023-10-23 16:20 UTC, hmeneuvrier commented on src/Form/SignalementErpType.php
> +                    new Assert\NotBlank(message: 'Veuillez indiquer si vous avez prevenu la compagnie de transport ?'),
il manque le é sur prévenu

2023-10-23 16:37 UTC, merged