[Sécurité] Commande de remise à zero des mots de passe administrateurs
MTES-MCT/stop-punaises pull request #481
Opened 2023-12-04 14:10 UTC by emilschn

## Ticket

#480    

## Description
Commande de remise à zero des mots de passe administrateurs

## Tests
- [ ] `make console app="reinit-admin-passwords"`
- [ ] L'admin ne peut plus se connecter
- [ ] Il a reçu un mail d'activation de compte et le lien dans le mail permet de saisir directement son mot de passe pour se réactiver

2023-12-04 15:17 UTC, numew requested changes
Je remarque que si on arrive sur un lien d'activation non valide on est redirigé sur la page de login page sur laquelle le message d'erreur (flash) ne s'affiche pas.

2023-12-04 15:17 UTC, numew commented on src/Command/ReinitAdminPasswordsCommand.php
> +
Pas besoin de générer le mot de passe ni de valider quoi que ce soit ici, je pense que 
`$user->setPassword('')->setStatus(Status::INACTIVE);`
serait suffisant

2023-12-05 08:22 UTC, emilschn commented on src/Command/ReinitAdminPasswordsCommand.php
> +
Ok, c'est modifié !

2023-12-05 08:33 UTC, hmeneuvrier commented
Même remarque que Numa.
Dans le mail le lien est sous la forme 
 link*0*=utf-8''http%3A%2F%2Flocalhost%3A8090%2Factivation-compte%2F8a86890b190b;
 Du coup c'est compliqué de trouver le bon lien, et si je tente http://localhost:8090/activation-compte/8a86890b190b je susi redirigée vers la page de login, mais sans message flash

2023-12-05 08:50 UTC, emilschn commented
> Même remarque que Numa. Dans le mail le lien est sous la forme link_0_=utf-8''http%3A%2F%2Flocalhost%3A8090%2Factivation-compte%2F8a86890b190b; Du coup c'est compliqué de trouver le bon lien, et si je tente http://localhost:8090/activation-compte/8a86890b190b je susi redirigée vers la page de login, mais sans message flash

Le champ est coupé en deux, il y a link0 et link1, il faut les unir et remplacer les caractères spéciaux, et ça fonctionne

2023-12-05 10:37 UTC, numew commented
> > Même remarque que Numa. Dans le mail le lien est sous la forme link_0_=utf-8''http%3A%2F%2Flocalhost%3A8090%2Factivation-compte%2F8a86890b190b; Du coup c'est compliqué de trouver le bon lien, et si je tente http://localhost:8090/activation-compte/8a86890b190b je susi redirigée vers la page de login, mais sans message flash
> 
> Le champ est coupé en deux, il y a link0 et link1, il faut les unir et remplacer les caractères spéciaux, et ça fonctionne

On peux quand même rajouter l'affichage des message flash sur la page login ? Car si le lien est expiré/invalide le message d'erreur ne s'affiche pas après la redirection, c'est assez perturbant

2023-12-05 11:11 UTC, emilschn commented
Il faut bien penser que c'est une fonctionnalité admin, on n'a pas trop besoin d'être au top de l'ergonomie :D

2023-12-05 11:36 UTC, numew approved these changes

2023-12-06 11:53 UTC, sfinx13 approved these changes

2023-12-06 13:36 UTC, hmeneuvrier approved these changes
OK pour moi

2023-12-06 13:36 UTC, merged