[Accessibilité] Ajouter une balise alt à toutes les images
MTES-MCT/stop-punaises pull request #509
Opened 2023-12-07 09:15 UTC by sfinx13

## Ticket

#487    

## Description
Ajout des de texte alternatifs manquant sur les images dont le logo.
[D'après Web-Aim, l'organisation qui promeut l'accessibilité sur le Web](https://webaim.org/techniques/alttext/#logos), un texte pour le logos est à prévoir mais sans le mot logo

## Changements apportés
* Ajout des textes sur les balises alt

## Pré-requis

## Tests
- [ ] Faire une recherche sur le projet sur la balise i<mg

2023-12-07 13:11 UTC, numew commented
On aurait pu un mieux plus décrire les images mais je valide

2023-12-08 10:46 UTC, emilschn requested changes

2023-12-08 10:46 UTC, emilschn commented on templates/front/index.html.twig
> +                <img src="{{ asset('build/images/loupe-punaise.png') }}" alt="illustration punaises" width="384" height="288">
c'est une image illustrative, c'est impératif de laisser vide

2023-12-08 10:46 UTC, emilschn commented on templates/front/index.html.twig
> +                    <img src="{{ asset('build/images/logo-stop-punaises.svg') }}" alt="Stop punaises">
c'est une image illustrative, c'est impératif de laisser vide

2023-12-08 11:29 UTC, sfinx13 commented on templates/front/index.html.twig
> +                <img src="{{ asset('build/images/loupe-punaise.png') }}" alt="illustration punaises" width="384" height="288">
ça marche, comme on trouve un peu tout et son contraire, tu peux poster la source pour mon info personnelle

2023-12-08 11:32 UTC, emilschn commented on templates/front/index.html.twig
> +                <img src="{{ asset('build/images/loupe-punaise.png') }}" alt="illustration punaises" width="384" height="288">
https://www.w3.org/WAI/tips/developing/fr#incluez-des-%C3%A9quivalents-textuels-pour-les-images
y'a une précision sur les images illustratives

2023-12-11 09:27 UTC, hmeneuvrier commented
Alt à retirer dans 
templates/bundles/TwigBundle/Exception/error.html.twig, ligne 18
templates/bundles/TwigBundle/Exception/error403.html.twig, ligne 16
templates/bundles/TwigBundle/Exception/error404.html.twig, ligne 16

(pour la même raison qu'évoquée par Emilien au-dessus)

2023-12-11 09:38 UTC, hmeneuvrier commented
Dans le BO ce ne sont pas des balises <img>, mais
```
<div class="fr-col-6 fr-col-md-3">
    <div style="background: url('{{ photo.url }}?_csrf_token={{ csrf_token('signalement_ext_file_view') }}')no-repeat center center/cover">
        <a class="fr-btn fr-icon-eye-line" href="{{ photo.url }}?_csrf_token={{ csrf_token('signalement_ext_file_view') }}" title="Voir la photo" target="_blank" rel="noopener"></a>
    </div>
</div>
```


- templates/common/components/signalement-detail.html.twig 
- templates/signalement_view/tab-intervention.html.twig
-

On peut utiliser
`aria-label="Titre de l'image" `

ou un texte qu'on cache en css

2023-12-12 15:03 UTC, hmeneuvrier approved these changes
Re-relecture OK

2023-12-12 15:09 UTC, merged