[Accessibilité] Mettre le poids des pdf à télécharger
MTES-MCT/stop-punaises pull request #539
Opened 2023-12-20 11:00 UTC by hmeneuvrier

## Ticket

#500    

## Description
Ajouter le poids des pdfs. La plupart des pdf sont envoyés par mail, j'ai ajouté le poids sur la page de suivi usager.

## Changements apportés
* Modification du controller et du twig pour afficher le poids
* Ajout d'une extension Twig  pour le formatage du poids

## Pré-requis

## Tests
- [ ] Faire un signalement en autotraitement, vérifier que dans la page de suivi le poids du pdf d'autotreaitement est bien affiché
- [ ] Faire un signalement en traitement pro, vérifier que dans la page de suivi usager le poids du pdf de préparation est bien affiché

2023-12-20 12:41 UTC, sfinx13 requested changes

2023-12-20 12:41 UTC, sfinx13 commented on src/Twig/AppExtension.php
>  }
Déplacer cette fonction dans une classe utilitaire, doit être appelé de manière statique et écrire un tu

2023-12-20 12:42 UTC, sfinx13 requested changes

2023-12-20 12:42 UTC, sfinx13 commented on src/Controller/Front/SuiviUsagerViewController.php
> +        }
initialiser le docSize à 0 et supprimer le else

2023-12-20 14:05 UTC, hmeneuvrier commented on src/Twig/AppExtension.php
>  }
ok traité

2023-12-20 14:05 UTC, hmeneuvrier commented on src/Controller/Front/SuiviUsagerViewController.php
> +        }
@sfinx13 retours traités

2023-12-20 15:43 UTC, numew reviewed
Je pense qu'il faut le rajouter aussi su le lien de la home page
![homepage_pdf](https://github.com/MTES-MCT/stop-punaises/assets/7130780/dda3437f-230e-4294-ac31-33045cfb64d3)
Et moins simple mais j'imagine que c'est attendu aussi dans la liste des événement
![evement_suivi_pdf](https://github.com/MTES-MCT/stop-punaises/assets/7130780/07a7454f-9307-40ae-b136-901a8c6e23ac)

2023-12-21 08:31 UTC, emilschn commented
Pour une information de cette sorte, est-ce qu'on va vraiment calculer le poids du même fichier à chaque affichage de la page ?
On ne peut pas conserver un poids approximatif dans le yaml, à côté du nom du fichier ? (1Mo)
Je pense que l'important n'est pas la précision mais l'ordre d'idée pour ce genre de chose, non ? Pour savoir combien de temps le téléchargement va prendre.
D'ailleurs, vu le contenu, y'a sûrement moyen d'optimiser un peu le pdf pour qu'il pèse moins lourd...?

2023-12-22 08:24 UTC, hmeneuvrier commented
> Pour une information de cette sorte, est-ce qu'on va vraiment calculer le poids du même fichier à chaque affichage de la page ? On ne peut pas conserver un poids approximatif dans le yaml, à côté du nom du fichier ? (1Mo) Je pense que l'important n'est pas la précision mais l'ordre d'idée pour ce genre de chose, non ? Pour savoir combien de temps le téléchargement va prendre. D'ailleurs, vu le contenu, y'a sûrement moyen d'optimiser un peu le pdf pour qu'il pèse moins lourd...?

Je m'étais effectivement posé la question, et j'avais failli faire comme ça. Puisque vous êtes tous OK, je vais changer !

2023-12-22 09:09 UTC, hmeneuvrier commented
@emilschn @numew @sfinx13 vos retours sont traités

2023-12-22 09:23 UTC, emilschn approved these changes
C'est ok pour moi !

2023-12-22 11:38 UTC, numew approved these changes

2023-12-22 11:39 UTC, merged