[wip] [BO - Signalements] Chargement de la liste en Ajax
MTES-MCT/stop-punaises pull request #546
Opened 2024-01-04 10:22 UTC by emilschn

## Ticket

#544    

## Description
Chargement de la liste des signalements du BO en Ajax

## Changements apportés
* 

## Pré-requis
`npm run watch`

## Tests
- [ ]

2024-01-05 14:43 UTC, numew reviewed
Deux retours assez importants, à part ça pas de soucis durant mes tests

2024-01-05 14:43 UTC, numew commented on src/Service/Signalement/TableLister.php
> +            start: null,
Pour les deux premières requêtes il faut faire un COUNT SQL sinon on charges toutes les données pour rien, pour moi le plus simple c'est d'ajouter un paramètre count que l'on passe à `findDeclaredByOccupants`

2024-01-05 14:43 UTC, numew commented on src/Service/Signalement/TableLister.php
> +        $requestColumns = $request->get('columns');
Il faut aussi récupérer le paramètre "order" (au clic sur l’entête des colonnes) et le gérer dans la query pour affiché les éléments dans l'ordre demandé

2024-01-08 09:23 UTC, emilschn commented
> Deux retours assez importants.
> 
> Lors de mes tests erreur suivante quand je me connecte en tant qu'entreprise : ![datatable_company](https://private-user-images.githubusercontent.com/7130780/294539949-3a7b8923-b3f0-405e-a154-95f780ad9adb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDI1NjMsIm5iZiI6MTcwNDcwMjI2MywicGF0aCI6Ii83MTMwNzgwLzI5NDUzOTk0OS0zYTdiODkyMy1iM2YwLTQwNWUtYTE1NC05NWY3ODBhZDlhZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDgyNDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGYzZjQxOWFkMTQ2ODZjMTE4ZDZmMTUxZjcxYTMxZDBkYjJmNDRlOWMzZjI0NWU0N2NmMDQ5NjE3YmIzNDMyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o--IhqEyjZwRAN_vrMk84LLcuIBvHE0rhVnxys_-opo)

Merci, c'est corrigé !

2024-01-08 09:24 UTC, emilschn commented on src/Service/Signalement/TableLister.php
> +            start: null,
C'est corrigé

2024-01-08 10:39 UTC, emilschn commented on src/Service/Signalement/TableLister.php
> +        $requestColumns = $request->get('columns');
Bien vu ! J'y avais pensé et j'ai oublié... C'est fait :)

2024-01-09 08:25 UTC, sfinx13 requested changes
Plus des retours d'architecture sur la manière de gérer les données provenant de DataTable. 
L'idée c'est de standardiser ce genre de dev par la suite si d'autre liste serait amené a être géré coté serveur. 

Je pense qu'il y'a des commentaires qui se répète, j'ai fait un schéma pour illustrer mes commentaires à ce niveau. Ouvert à la discussion 
![image](https://github.com/MTES-MCT/stop-punaises/assets/5757116/bfbf3faf-c094-45d7-99ae-c3dceffbdca5)

2024-01-09 08:25 UTC, sfinx13 commented on src/Service/Signalement/StatutFormat.php
> +                $this->label = 'Traité';
A voir si on aurait pas des constantes ou un énum deja existant pour les libéllé de statut, les créer dans le cas contraire

2024-01-09 08:25 UTC, sfinx13 commented on src/Service/Signalement/TableLister.php
> +class TableLister
Pour TableLister si je n'avais pas lu le descriptif de la PR je n'aurais pas su que c'était le service qui gère les requêtes DataTable, il faudrait rendre le nom plus explicite, je propose `DataTableHandler`

2024-01-09 08:25 UTC, sfinx13 commented on src/Service/Signalement/TableLister.php
> +    public function list(Request $request): array
Au lieu d'avoir une méthode `list()` plutôt `handleRequest()` et on devrait avoir un objet qui se représenterait les données envoyées par DataTable

2024-01-09 08:25 UTC, sfinx13 commented on src/Service/Signalement/TableLister.php
> +        $orderDirection = $requestOrder[0]['dir'];
Je pense qu'on pourrais simplifier le code en passant par un objet DTO Request
D'apres ce que j'ai vu de datatable coté serveur, ça ressemblerat à ça (utilisable pour toutes les requetes datatable peu importe la liste)

```php
class DataTableRequest
{
    private ?string $orderColumn = null;
    private ?string $orderDir = null;
    private array $search = [];

    public function __construct(
        private ?int    $draw = null,
        private int     $start = 0,
        private int     $length = 0,
        private ?array  $columns = null,
        private ?array  $order = null,
    ) {
        $this->orderColumn = $this->order[0]['column'] ?? 0;
        $this->orderDir = $this->order[0]['dir'] ?? 'ASC';
        if (!empty($this->columns)) {
            foreach ($this->columns as $item) {
                 // ex ['ville' => 'Mars']
                $this->search[$item['data']] = $item['search']['value'] ?? null;
            }
        }
    }
// getter
```

Injectable directement grâce au valueResolver
https://symfony.com/doc/current/controller/value_resolver.html#adding-a-custom-value-resolver

```php
namespace App\ValueResolver;

class DataTableRequestResolver implements ValueResolverInterface
{
    public function supports(Request $request, ArgumentMetadata $argumentMetadata)
    {
        return $argumentMetadata->getType() === DataTableRequest::class;
    }

    public function resolve(Request $request, ArgumentMetadata $argument): iterable
    {
        $queryParameter = $request->query->all();
        if ($this->supports($request, $argument)) {
            yield new DataTableRequest(
                $queryParameter['draw'] ?? null,
                $queryParameter['start'] ?? 0,
                $queryParameter['length'] ?? DataTableRequest::MAX_RESULTS,
                $queryParameter['columns'] ?? null,
                $queryParameter['order'] ?? null
            );
        }
    }
}
```

2024-01-09 08:25 UTC, sfinx13 commented on src/Service/Signalement/TableLister.php
> +        );
Dis plus haut avec la pagination doctrine, plus besoin de faire une requête count

2024-01-09 08:25 UTC, sfinx13 commented on src/Service/Signalement/TableLister.php
> +        );
doctrine paginator peut le gérer

2024-01-09 08:25 UTC, sfinx13 commented on src/Service/Signalement/TableLister.php
> +            $signalementsFilteredFormated[] = $signalementFormatted;
Avoir un méthode dans le manager qui retourner les résultat au format "DataTable" ?

2024-01-09 08:25 UTC, sfinx13 commented on src/Service/Signalement/TableLister.php
> +        ];
Avoir un objet qui représente la réponse DataTable ça permet de standardiser nos dev pour de futur traitement datatable en back

```php
class DataTable
{
    public function __construct(
        private int $draw = 0,
        private int $recordsTotal = 0,
        private int $recordsFiltered = 0,
        private array $data = []
    ) {
    }
   // getter

    public function toArray(): array
    {
        return [
            "draw" => $this->draw,
            "recordsTotal" => $this->recordsTotal,
            "recordsFiltered" => $this->recordsFiltered,
            "data" => $this->data
        ];
    }

2024-01-09 08:25 UTC, sfinx13 commented on src/Service/Signalement/TableLister.php
> +    }
Si la classe devient générique ce mapping devrait être ailleurs

2024-01-09 08:25 UTC, sfinx13 commented on src/Service/Signalement/TableLister.php
> +    }
Plutôt dans un manager dédié à data table ? `SignalementDataTableManager`

2024-01-09 08:25 UTC, sfinx13 commented on src/Service/Signalement/TableLister.php
> +    }
Plutôt un getter dans l'entité Signalement

2024-01-09 08:25 UTC, sfinx13 commented on src/Service/Signalement/TableLister.php
> +    }
Pareil plutôt renvoyer ces libellés dans un getter dédié depuis l'entité signalement

2024-01-09 08:25 UTC, sfinx13 commented on src/Service/Signalement/TableLister.php
> +}
Même remarque plutôt dans un manager dédié à data table ? SignalementDataTableManager

2024-01-09 08:31 UTC, sfinx13 commented on src/Service/Signalement/ProcedureFormat.php
> +            }
Je vois que l'échelle n'est pas la même pour un auto traitement, faudrait avoir des enum différent

2024-01-09 08:54 UTC, emilschn commented on assets/controllers/list_signalement.js
> +    options.pageLength = 20;
C'est géré en back, mais le back reçoit la longueur depuis le front, donc depuis ici.

2024-01-09 10:08 UTC, emilschn commented on src/Repository/SignalementRepository.php
> +                    break;
J'avais commencé comme ça, mais il y a des critères avec plusieurs orderBy, et du coup, ça n'allait pas.

2024-01-09 10:09 UTC, emilschn commented on src/Service/Signalement/ProcedureFormat.php
> +    }
J'ai mergé la modification que j'ai faite dessus, j'ai fait différemment, mais c'est une seule méthode statique aussi.

2024-01-09 10:19 UTC, sfinx13 commented on assets/controllers/list_signalement.js
> +    options.pageLength = 20;
Comme c'est pas modifiable et ça enverra toujours 20, on peut le mettre en constante coté back ?

2024-01-09 10:31 UTC, emilschn commented on assets/controllers/list_signalement.js
> +    options.pageLength = 20;
Si on fait ça, je ne suis pas sûr que datatable gère correctement la pagination :)
Il doit être conscient du nombre d'éléments à afficher en front pour renvoyer la bonne pagination.

2024-01-09 12:59 UTC, emilschn commented on src/Service/Signalement/TableLister.php
> +}
Cette remarque s'applique à quoi ?

2024-01-09 13:00 UTC, emilschn commented on src/Service/Signalement/ProcedureFormat.php
> +            }
Il faudra voir ce que j'ai fait sur la nouvelle classe

2024-01-09 13:00 UTC, emilschn commented on src/Service/Signalement/ProcedureFormat.php
> +    public static function getPercentByLabel(string $label): int
Ajouter TU correspondant

2024-01-11 11:01 UTC, emilschn commented on src/Controller/AjaxSignalementListController.php
> +        );
OK !

2024-01-11 11:07 UTC, emilschn commented on src/Repository/SignalementRepository.php
> +        }
le COUNT a disparu de la requête

2024-01-11 13:37 UTC, emilschn commented on src/Service/Signalement/StatutFormat.php
> +class StatutFormat
OK

2024-01-11 14:08 UTC, emilschn commented on src/Service/Signalement/ProcedureFormat.php
> +                    }
OK

2024-01-11 14:09 UTC, emilschn commented on src/Service/Signalement/ProcedureFormat.php
> +    public static function getPercentByLabel(string $label): int
caduc

2024-01-11 14:37 UTC, emilschn commented on src/Service/Signalement/StatutFormat.php
> +                $this->label = 'Traité';
OK

2024-01-11 14:38 UTC, emilschn commented on src/Service/Signalement/TableLister.php
> +    }
l'entité n'est plus utilisée ici

2024-01-11 14:38 UTC, emilschn commented on src/Service/Signalement/TableLister.php
> +    }
l'entité n'est plus utilisée ici

2024-01-11 15:24 UTC, emilschn commented on src/Service/Signalement/TableLister.php
> +    public function list(Request $request): array
OK

2024-01-11 16:43 UTC, emilschn commented on src/Controller/AjaxSignalementListController.php
> +        Request $request,
OK !

2024-01-11 16:43 UTC, emilschn commented on src/Service/Signalement/TableLister.php
> +        $orderDirection = $requestOrder[0]['dir'];
OK

2024-01-12 11:05 UTC, hmeneuvrier commented
Test : je viens d'avoir une alerte erreur "DataTables warning: table id=datatable-ajax - Ajax error. For more information about this error, please see https://datatables.net/tn/7" lors du rafraichissement de la liste, après création du 18è signalement qui était un signalement en logement social

Dans le profiler : 

`App\Service\Signalement\SignalementOccupantDataTableHandler::formatNiveauInfestation(): Argument #1 ($niveauInfestation) must be of type string, null given, called in /app/src/Service/Signalement/SignalementOccupantDataTableHandler.php on line 135`

2024-01-12 13:33 UTC, hmeneuvrier commented
J'ai accepté et envoyé une estimation avec l'entreprise 1 pour le signalement 2024-7 : 
- le signalement apparait au statut "en cours"
- je me connecte en admin, le signalement est au statut "en cours"
- je me connecte avec l'entreprise 7, le signalement est au statut "en cours", je l'ouvre et je le refuse, je reviens sur la liste des signalements, il apparait 2 fois, une fois avec le statut "en cours", une fois avec le statut "refusé" : 

![image](https://github.com/MTES-MCT/stop-punaises/assets/33071753/a4cfb79d-5803-413c-b353-8300d9c4d21f)

2024-01-15 12:55 UTC, emilschn commented
> Test : je viens d'avoir une alerte erreur "DataTables warning: table id=datatable-ajax - Ajax error. For more information about this error, please see https://datatables.net/tn/7" lors du rafraichissement de la liste, après création du 18è signalement qui était un signalement en logement social
> 
> Dans le profiler :
> 
> `App\Service\Signalement\SignalementOccupantDataTableHandler::formatNiveauInfestation(): Argument #1 ($niveauInfestation) must be of type string, null given, called in /app/src/Service/Signalement/SignalementOccupantDataTableHandler.php on line 135`

OK corrigé !

2024-01-15 14:07 UTC, emilschn commented
@hmeneuvrier le deuxième point est corrigé aussi

2024-01-15 15:27 UTC, hmeneuvrier commented
Concernant l'erreur sur le niveau d'infestation à null pour les logemenst sociaux : 

Pour le signalement en logement social qui n'a pas de Niveau d'infestation, il apparait avec le label 0 - Nulle, mais si on choisit ce niveau dans le filtre, il n'apparait plus.
Il me paraitrait plus cohérent d'ajouter un tag N/C (même si j'imagine que c'était le fonctionnement avant tes modifications... peut-être juste créer un ticket)

2024-01-15 15:28 UTC, hmeneuvrier commented
Concernant le deuxième point c'est maintenant ok en admin, mais avec la company 7, le signalement apparait toujours 2 fois : 

![image](https://github.com/MTES-MCT/stop-punaises/assets/33071753/96e76225-57b6-4ed3-92f1-7c26d61cf2b9)

2024-01-18 09:46 UTC, sfinx13 requested changes

2024-01-18 10:50 UTC, emilschn commented on src/Repository/SignalementRepository.php
> +        }
@sfinx13 en plus j'y avais pensé, mais j'ai oublié...
Merci ! C'est corrigé.
J'en ai profité pour corriger un test fonctionnel, aucune idée de pourquoi il ne bloquait pas jusque là...

2024-01-18 12:26 UTC, hmeneuvrier commented
> Concernant le deuxième point c'est maintenant ok en admin, mais avec la company 7, le signalement apparait toujours 2 fois :

@emilschn c'est ok pour moi maintenant

2024-01-18 12:27 UTC, hmeneuvrier approved these changes
Test OK, et relecture superficielle (désolée) OK

2024-01-18 13:08 UTC, sfinx13 approved these changes

2024-01-18 13:09 UTC, merged