Feature/634 title page list
MTES-MCT/stop-punaises pull request #666
Opened 2024-02-13 15:36 UTC by numew

## Ticket

#634

## Description
Les titres de page contenant des liste datatable sont modifiés dynamiquement pour ressembler à ça "Les signalements usagers - 1 signalement trouvé - page 1 sur 1 - Stop punaises"

## Tests
- [ ] Vérifier que les titre des pages correspondent bien au contenu de la page

2024-02-13 15:59 UTC, emilschn requested changes
Pas encore test, 1 retour multiple de code

2024-02-13 15:59 UTC, emilschn commented on templates/entreprise_list/index.html.twig
> -            <h2><span id="count-entreprise">{{ count_entreprises }}</span> entreprises trouvées</h2>
Supprimer l'initialisation de `count_entreprises` dans le controller

2024-02-13 15:59 UTC, emilschn commented on templates/signalement_list/erp-transports.html.twig
> -        <h2><span id="count-signalement">{{ count_signalement }}</span> signalements trouvés</h2>
Supprimer les initialisations de `count_signalement` dans le controller

2024-02-16 09:45 UTC, numew commented on templates/signalement_list/erp-transports.html.twig
> -        <h2><span id="count-signalement">{{ count_signalement }}</span> signalements trouvés</h2>
Ok

2024-02-16 11:09 UTC, emilschn commented
Un petit KO : la page en cours n'est pas mise à jour dans le title quand on est sur une liste d'entreprise.
Reste des tests OK !
Et lecture aussi.

2024-02-16 15:41 UTC, hmeneuvrier approved these changes
Relecture et test OK (c'est classe!)

2024-02-19 09:18 UTC, emilschn approved these changes
Ok lecture et test

2024-02-19 09:18 UTC, merged