[Accessibilité - Audit] [Formulaire signalement - 11.13] Faciliter remplissage automatique
MTES-MCT/stop-punaises pull request #667
Opened 2024-02-13 15:44 UTC by sfinx13

## Ticket

#623    

## Description
Description de la modification apportée

## Changements apportés
* Ajout attribut autocomplete contextualisé sur les champs de formulaire

## Pré-requis

## Tests
- [ ] Formulaire de dépôt de signalement
- [ ] Formulaire de création de signalement BO
- [ ] Formulaire création entreprise
- [ ] Formulaire création employé
- [ ] Formuaire Login
- [ ] Formualires Request and Reset password

2024-02-13 16:04 UTC, emilschn commented on src/Form/EntrepriseType.php
> +                    'placeholder' => 'claude.petit@courriel.fr',
mettre un placeholder en liaison avec l'organisation ?

2024-02-13 16:07 UTC, emilschn commented on src/Form/SignalementFrontType.php
> +                    'autocomplete' => 'nom',
`organization` ? en tout cas, pas `nom` :)

2024-02-13 16:08 UTC, emilschn requested changes
2 retours, pas encore testé !

2024-02-13 16:27 UTC, sfinx13 commented
> 2 retours, pas encore testé !

Ok retours traités

2024-02-16 09:37 UTC, emilschn approved these changes
OK lecture et test

2024-02-16 10:07 UTC, numew approved these changes
Test et relecture OK

2024-02-16 10:07 UTC, merged