[Accessibilité - Audit] [Correction des liens - 6.1 ET 13.5]
MTES-MCT/stop-punaises pull request #706
Opened 2024-03-07 17:28 UTC by sfinx13

## Ticket

#698    

## Description
Revue de liens
## Changements apportés
* Mise à jour lien statique
* Mise à jour lien dynamique

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2024-03-08 08:24 UTC, emilschn commented on assets/controllers/list_employes.js
> -        previous: "&lt; Page précédente",
il faut quand même garder Page précédente / suivante, comme sur les autres, non ?

2024-03-08 08:27 UTC, emilschn commented on assets/controllers/list_signalement.js
> +      $('#datatable_paginate').attr('role', 'navigation');
je pense qu'il faut faire  
`if ($('#datatable_paginate').length > 0)` 
pour l'appliquer, pour éviter des erreurs

2024-03-08 08:27 UTC, emilschn commented on assets/controllers/list_signalement.js
>        $('#datatable-ajax_paginate').attr('role', 'navigation');
je pense qu'il faut faire  
`if ($('#datatable-ajax_paginate').length > 0)` 
pour l'appliquer, pour éviter des erreurs

2024-03-08 08:28 UTC, emilschn commented on templates/front/index.html.twig
> -                        <a href="tel:+33806706806" title="Appeler le service Info logement indigne">0806 706 806</a>.
il faut garder `indigne` quand même, je pense

2024-03-08 08:28 UTC, emilschn commented on templates/front_signalement/_partial_step_info_usager.html.twig
> +            <a href="tel:+33806706806" title="Appeler le service Info logement au 0806 706 806">0806&nbsp;706&nbsp;806</a>
il faut garder `indigne` quand même, je pense

2024-03-08 08:28 UTC, emilschn requested changes
Quelques retours, pas encore testé !

2024-03-08 09:38 UTC, emilschn requested changes
Un retour de test :
Sur la page information, il faudrait modifier le title du numéro de téléphone aussi (c'était pas relevé, donc je l'avais loupé, désolé !)

2024-03-08 10:17 UTC, sfinx13 commented
> Un retour de test : Sur la page information, il faudrait modifier le title du numéro de téléphone aussi (c'était pas relevé, donc je l'avais loupé, désolé !)

Pas de souci, je l'ai aussi appliqué sur la page de contact

2024-03-11 10:27 UTC, emilschn approved these changes
OK pour moi !

2024-03-11 10:36 UTC, hmeneuvrier approved these changes
Tests et relecture OK

2024-03-11 10:36 UTC, merged