[Accessibilité - Audit] [Dépot de signalement - 6.1 ET 11.2 ET 11.10] Ajustements champs du formulaire
MTES-MCT/stop-punaises pull request #707
Opened 2024-03-08 08:27 UTC by sfinx13

## Ticket

#700    

## Description
Description de la modification apportée

## Changements apportés
* Initialisation d'un thème de formulaire pour que `form_label` génère un span `<span class="fr-hint-text">` à l'intérieur d'un `<label>` conforme au DSFR
*  Mise à jour du label du toggle d'adresse par Saisie manuelle de l’adresse
*  Correction des liaisons manquantes entre le message d'erreur et les input via `aria-describedby`
 
## Pré-requis
Inspecteur ouvert

## Tests
- [ ] [FO] Lors du dépôt du formulaire vérifier le message du toggle est bien mise à jour
- [ ] [FO][BO] Sur tous les formulaires, vérifier que les messages d'érreur sont bien lié via `aria-describedby`
- [ ] [FO][BO] Sur tous les formulaires, vérifier que les les span d'aide sont à l'intérieur du label

2024-03-08 08:31 UTC, sfinx13 commented on templates/common/form/custom_theme.html.twig
> +{% use 'form_div_layout.html.twig' %}
j'ai trouvé ce thème dsfr qui s'appuie sur la 1.7 (on est en 1.11) 
https://github.com/radicaldingos/dsfr-form-theme-bundle/blob/main/Resources/views/Form/dsfr_form_theme.html.twig

J'ai juste initié et pris uniquement le block form_label (à terme faudra ajouter les autre bloc et adapater si besoin)

2024-03-08 08:31 UTC, sfinx13 commented on templates/common/form/custom_theme.html.twig
> +            {% set label_attr = label_attr|merge({'class': (label_attr.class|default(''))|trim}) %}
legere adapation pour pas avoir le class fr-label sur les label de input radio

2024-03-08 09:46 UTC, emilschn requested changes
Un mini-retour de typo (pas encore testé)

2024-03-11 11:00 UTC, hmeneuvrier commented
Quand on a eu une erreur sur un champ, qu'on la corrige, on a toujours le aria-describedby, je ne sais pas si c'esst grave : 
![image](https://github.com/MTES-MCT/stop-punaises/assets/33071753/e3b18690-a45d-4ae6-a7ed-37b4166d16ff)

2024-03-11 16:49 UTC, sfinx13 commented
> Quand on a eu une erreur sur un champ, qu'on la corrige, on a toujours le aria-describedby, je ne sais pas si c'esst grave :

Je ne sais pas

2024-03-12 13:05 UTC, emilschn approved these changes
Ok pour tests et relecture !

2024-03-12 15:30 UTC, emilschn commented on assets/controllers/form_signalement.js
> +  } else {
else inutile

2024-03-12 15:41 UTC, sfinx13 commented on assets/controllers/form_signalement_front.js
> +      });
@emilschn @hmeneuvrier

2024-03-12 16:52 UTC, hmeneuvrier approved these changes
Relecture et tests OK

2024-03-12 16:55 UTC, merged