Fixer des contraintes de longueur et de complexité des mots de passe
MTES-MCT/stop-punaises pull request #715
Opened 2024-03-13 14:37 UTC by numew

## Ticket

#551

## Description
Ajout de contraintes de validation pour des mot de passe plus fort : 
- 8 caractères minimum
- 1 caractère majuscule minimum
- 1 caractère minuscule minimum
- 1 chiffre minimum
- 1 caractère spécial minimum

## Changements apportés
- Passage de l'app en français par défaut
- Route unique `activate_account` pour activer son compte / modifier sont mot de passe
- Ajout de l'option "Afficher" sur les champs mot de passe de la page création/modification de mot de passe
- Affichage du message flash de succès aprés redirection sur la page login
- Ajout de tests

## Pré-requis
`make npm-build`

## Tests
- [ ] Vérifier que l'activation de compte / modification du mot de passe fonctionne correctement
- [ ] Vérifier que les indicateurs de contrainte évoluent correctement au fur et à mesure de la complétion du champs

2024-03-14 14:02 UTC, emilschn commented on src/Entity/User.php
> +    #[Assert\Length(min: 8, max: 200, minMessage: 'Le mot de passe doit contenir au moins {{ limit }} caratères.', groups: ['password'])]
caractères (manque un c)

2024-03-14 14:02 UTC, emilschn commented on src/Entity/User.php
> +    #[Assert\NotEqualTo(propertyPath: 'email', message: 'Le mot de passe ne doit pas être votre email.', groups: ['password'])]
e-mail

2024-03-14 14:06 UTC, emilschn commented on templates/security/reset_password_new.html.twig
> +                                Les mots de passes ne correspondent pas.
pas de "s" à la fin de passe

2024-03-14 14:11 UTC, emilschn commented on templates/security/login.html.twig
> +		<div role="status" class="fr-alert fr-alert--{{ label }} fr-alert--sm fr-mb-3v">
ajouter un `id` à cette `<div>` et y faire référence depuis les champs avec `aria-describedby`

2024-03-14 14:14 UTC, emilschn commented on tests/Unit/Entity/UserTest.php
> +        yield 'short' => ['Le mot de passe doit contenir au moins 8 caratères', 'short'];
manque "c" dans caractères

2024-03-14 14:15 UTC, emilschn requested changes
Retours de typo et accessibilité

2024-03-14 14:53 UTC, numew commented on src/Entity/User.php
> +    #[Assert\Length(min: 8, max: 200, minMessage: 'Le mot de passe doit contenir au moins {{ limit }} caratères.', groups: ['password'])]
Ok, merci

2024-03-14 14:53 UTC, numew commented on templates/security/reset_password_new.html.twig
> +                                Les mots de passes ne correspondent pas.
Ok

2024-03-14 14:59 UTC, numew commented on templates/security/reset_password_new.html.twig
> +                    <div role="status" class="fr-alert fr-alert--{{ label }} fr-alert--sm fr-mb-3v">
Comme tu l'indique il faudrait un index donc ce serait bancal de les référencer via aria-describedby (ce n'est pas en place sur le reste du site)

2024-03-14 16:17 UTC, emilschn commented on templates/security/login.html.twig
> +		<div role="status" class="fr-alert fr-alert--{{ label }} fr-alert--sm fr-mb-3v">
Ca n'affiche pas les messages d'erreur au même endroit ?

2024-03-15 09:11 UTC, sfinx13 requested changes

2024-03-15 09:11 UTC, sfinx13 commented on src/Service/Mailer/MailerProvider.php
> +        $link = $this->urlGenerator->generate('activate_account', ['id' => $user->getId(), 'token' => $user->getToken()]);
Il faudrait ajouter un nouveau champ uuid et se baser dessus sur les envois de lien

2024-03-15 15:27 UTC, numew commented on templates/security/reset_password_new.html.twig
> +                    <div role="status" class="fr-alert fr-alert--{{ label }} fr-alert--sm fr-mb-3v">
Ok

2024-03-15 15:30 UTC, numew commented on src/Service/Mailer/MailerProvider.php
> +        $link = $this->urlGenerator->generate('activate_account', ['id' => $user->getId(), 'token' => $user->getToken()]);
Sérieusement ?

2024-03-19 14:43 UTC, numew commented on src/Service/Mailer/MailerProvider.php
> +        $link = $this->urlGenerator->generate('activate_account', ['id' => $user->getId(), 'token' => $user->getToken()]);
Ok, comme la version avec le seul token ne me convient pas, j'ai mis en place la version avec uuid qui tu as demandé initialement.

2024-03-22 07:47 UTC, sfinx13 approved these changes
Lecture et test OK

2024-03-29 15:10 UTC, numew commented
@hmeneuvrier retours traités, merci.

2024-03-29 15:39 UTC, hmeneuvrier approved these changes
OK pour moi

2024-03-29 15:40 UTC, merged