[Sécurité] Contrôle des entrées du formulaire "Dans mon logement" pour les champs ajouté via le SignalementFrontType
MTES-MCT/stop-punaises pull request #789
Opened 2024-09-20 14:43 UTC by numew

## Ticket

#788

## Description
Contrôle des entrées du formulaire "Dans mon logement" pour les champs ajouté via le `SignalementFrontType`

Les champs ajoutés coté front et gérés via `$form->getExtraData();` devront être traités séparément (voir https://github.com/orgs/MTES-MCT/projects/3/views/1?pane=issue&itemId=69962668)

## Changements apportés
* Ajout de contraintes sur les champs géré via le système classique de Symfony

## Tests
- [ ] Essayer de valider la soumission d'un formulaire de signalement "Dans mon logement" contenant des valeurs incohérentes

2024-09-20 15:14 UTC, hmeneuvrier commented on src/Entity/Signalement.php
> +        message: 'Veuillez renseigner une adresse email valide.',
e-mail

2024-09-20 15:37 UTC, hmeneuvrier commented
Les tests sont OK. C'est juste bizarre pour le numéro de téléphone, on a un texte qui dit "10 caractères max", et on peut en mettre 20

2024-09-20 16:02 UTC, numew commented on src/Entity/Signalement.php
> +        message: 'Veuillez renseigner une adresse email valide.',
ok

2024-09-23 10:30 UTC, emilschn commented on src/Entity/Signalement.php
> +        message: 'Veuillez renseigner votre numéro de téléphone.',
J'ai pu soumettre un formulaire avec `09090909090909PPP`

2024-09-23 10:31 UTC, emilschn commented on src/Entity/Signalement.php
> +        pattern: '/^[0-9]{5}$/',
J'ai pu soumettre ce code postal : `448501`

2024-09-23 11:36 UTC, emilschn commented on src/Entity/Signalement.php
> +        message: 'Veuillez renseigner une adresse e-mail valide.',
J'ai transmis une adresse mail non-valide. J'ai eu une erreur 500. Mais ça a quand même enregistré le signalement.

2024-09-23 11:37 UTC, emilschn requested changes
J'ai fait des tests d'envoi de formulaire pour tester la partie back.
J'ai noté mes retours.

2024-09-24 12:23 UTC, emilschn commented on src/Entity/Signalement.php
> +        message: 'Veuillez renseigner votre numéro de téléphone.',
Retour caduc, j'avais mal testé

2024-09-24 12:23 UTC, emilschn commented on src/Entity/Signalement.php
> +        message: 'Veuillez renseigner une adresse e-mail valide.',
Retour caduc, j'avais mal testé

2024-09-24 12:24 UTC, emilschn commented on src/Entity/Signalement.php
> +        pattern: '/^[0-9]{5}$/',
Retour caduc, j'avais mal testé

2024-09-24 12:25 UTC, emilschn approved these changes
Lecture et tests ok !

2024-09-27 08:55 UTC, merged