[QA] Archiver une entreprise
MTES-MCT/stop-punaises pull request #809
Opened 2024-10-09 09:43 UTC by numew

## Ticket

#804

## Description
Ajout d'une feature SA permettant d'archiver/désarchiver des entreprises (via la modification du statut de leur user)
![Screenshot 2024-10-09 at 11-38-24 Les entreprises partenaires - 68 entreprises trouvées - page 1 sur 4 - Stop punaises](https://github.com/user-attachments/assets/083b5e86-9e00-44be-a376-84bc96adcf0b)

## Pré-requis
`make npm-build`

## Tests
- [ ] S'assurer qu'il n'y a pas d'autres action à effectuer pour archiver une entreprise ?

2024-10-10 08:38 UTC, sfinx13 reviewed
J'ai archivé 2 compagnies sur 3 dans le 13, les 3 continuent de recevoir le signalement 

![image](https://github.com/user-attachments/assets/0455a1ea-58b6-404a-8539-7f09f4780a85)


![image](https://github.com/user-attachments/assets/56d0507d-6663-4d6f-a75a-101e02361229)

2024-10-10 08:43 UTC, sfinx13 reviewed
Je verrai une couleur verte pour le statut actif (A checker avec Mathilde)

2024-10-10 08:45 UTC, emilschn requested changes
Ce que tu as fait fonctionne pour l'authentification
Mais les entreprises "ARCHIVE" continuent de recevoir les mails de notifications quand un signalement est créé. Je pense qu'il faut au moins modifier ça.

Après, se pose la question de ce que deviennent les interventions déjà commencées par une entreprise. Mais peut-être pas nécessaire pour cette PR ?

2024-10-14 09:20 UTC, numew commented
> Je verrai une couleur verte pour le statut actif (A checker avec Mathilde)

J'ai harmoniser avec les statuts de signalements

2024-10-14 09:22 UTC, numew commented
> Ce que tu as fait fonctionne pour l'authentification Mais les entreprises "ARCHIVE" continuent de recevoir les mails de notifications quand un signalement est créé. Je pense qu'il faut au moins modifier ça.
> 
> Après, se pose la question de ce que deviennent les interventions déjà commencées par une entreprise. Mais peut-être pas nécessaire pour cette PR ?

J'ai contrôlé les différents mail envoyé aux entreprise pour ne les envoyer qu'au entreprise avec l'utilisateur actif. J'ai en conséquence adapter les template pour indiquer que l'entreprise n'était plus active pour les cas des échanges et proposition de devis des entreprise

2024-10-14 09:58 UTC, emilschn commented on src/Controller/SignalementMessageController.php
> +            return $this->json(['message' => 'Vous ne pouvez pas envoyez de message en tant qu\'admin.'], Response::HTTP_FORBIDDEN);
envoyer

2024-10-15 12:31 UTC, emilschn approved these changes
OK lecture et tests

2024-10-17 11:56 UTC, sfinx13 approved these changes
Lecture et test OK

2024-10-17 11:56 UTC, merged